apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: twitter-source
spec:
  env:
    - name: QUERY
      valueFrom:
        configMapKeyRef:
          key: QUERY
          name: twitter-serverless-events-config
    - name: WEBHOOK_NAME
      valueFrom:
        configMapKeyRef:
          key: WEBHOOK_NAME
          name: twitter-serverless-events-config
    - name: D_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: D_ACCESS_TOKEN
          name: twitter-serverless-events-secret
  image: janiew/discord-serverless-source:prod-latest
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: default